### ISSUE TITLE
2.1.3 bug report

### ISSUE THREAD

**Issue by exander77** [onsightit/web-wallet#4]
1. Cannot login with masterAccount and masterPassword, if masterAccount is not in email format. I am getting: Please enter a valid email address.
2. public/wallet/js/viewmodels/wallet-status.js: command links does not respect chDir
3. public/wallet/js/viewmodels/console/console.js: command does not respect chDir
4. views/login.ejs: password reset link does not repsect chDir

**Comment by exander77** [comment]
5. links inside emails do not respect chDir
6. change password link in user settings does not repsect chDir
7. new user do not set his password, after email verification, the user is redirected into settings, he can use change password link, but do not his old password, because it was not set

**Comment by onsightit** [comment]
I believe all but 7 are now resolved.  Still working on a few minor issues.

**Comment by magicleagues** [comment]
Hello Thx for your Work ..

installed today
I will like the tested.

install ok
launch ok

```
*** Starting web-wallet ...

Running node-supervisor with
  program 'wallet.js'
  --watch 'wallet.js, lib, public, roads, views'
  --extensions 'node, js'
  --exec 'node'

Starting child process with 'node wallet.js'
Watching directory '/root/web-wallet-2.1.1.1/wallet.js' for changes.
Press rs for restarting the process.
Watching directory '/root/web-wallet-2.1.1.1/lib' for changes.
Press rs for restarting the process.
Watching directory '/root/web-wallet-2.1.1.1/public' for changes.
Press rs for restarting the process.
Watching directory '/root/web-wallet-2.1.1.1/routes' for changes.
Press rs for restarting the process.
Watching directory '/root/web-wallet-2.1.1.1/views' for changes.
Press rs for restarting the process.
Database: localhost: 27017 / posdb
Base URL is: /
Express Server starting ...
(node: 17264) DeprecationWarning: `open ()` is deprecated in mongoose> = 4.11.0, use `openUri ()` instead, or set the `useMongoClient` option if using` connect () `or` createConnection () ` . See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client
Server is listening on: http: // localhost: 80
Wallet is listening on: http://127.0.0.1:16775
Db.prototype.authenticate method will be available in the following major release 3.x as MongoDB 3.6 will only allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Database connected.
Init-Wallet: Found MASTER_ACCOUNT's wallet for the YourCoin node_id on: 127.0.0.1
GET / login 200 21.035 ms - 3291
GET / 304 12.891 ms - -
GET / 200 4.704 ms - 2938
GET / 200 3.215 ms - 2938
```

points surely to see again .. after

currently I can not manage to connect myself Master
could you help me ..

regards,

**Comment by cryptonana** [comment]
after run web-wallet.sh i see this error

Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/web-wallet/lib/settings.js:9:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
Program node wallet.js exited with code 1

**Comment by Velescore** [comment]
npm install –save moment
shoudl fix your problem cryptonana

**Comment by LIZCOIN** [comment]
Hello,

Thank you for developing a web-wallet

I have this problem:

1. problem about user email verification. Email verification is not sent to the user and does not get any code.

2. Problem when login MASTER on https mod. When Login Master is not working and requires email but when entering master email it does not find any data.

I hope you can help explain here
