### ISSUE TITLE
Errors after run web-wallet.sh

### ISSUE THREAD

**Issue by cryptonana** [onsightit/web-wallet#7]
after run web-wallet.sh i see this error

Error: Cannot find module 'moment'
at Function.Module._resolveFilename (module.js:326:15)
at Function.Module._load (module.js:277:25)
at Module.require (module.js:354:17)
at require (internal/module.js:12:17)
at Object. (/root/web-wallet/lib/settings.js:9:14)
at Module._compile (module.js:410:26)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Module.require (module.js:354:17)
Program node wallet.js exited with code 1

**Comment by SwissCoin-Classic** [comment]
https://stackoverflow.com/questions/39413119/error-cant-find-npm-module-moment

**Comment by cryptonana** [comment]
after run this command 

npm install --save

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.Client.auth (/root/web-wallet/lib/coin-client.js:113:46)
    at Object.<anonymous> (/root/web-wallet/lib/coinapi.js:15:8)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/web-wallet/wallet.js:19:12)
Program node wallet.js exited with code 1

**Comment by cryptonana** [comment]
@SwissCoin-Classic which OS you use and can you please send me complete commands

**Comment by cryptonana** [comment]
now i was use old nodejs thats why come problem

can you please tell me i try to login with masteruser and pass but not login

**Comment by SwissCoin-Classic** [comment]
On Debian 9.0 

npm install module

**Comment by cryptonana** [comment]
every thing ok but login not work what i doing

**Comment by SwissCoin-Classic** [comment]
Logfile?

**Comment by SwissCoin-Classic** [comment]
mongodb online?

**Comment by cryptonana** [comment]
when i connect

Server is listening on: http://localhost:8181
Wallet is listening on: http://127.0.0.1:39868
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Database connected.
Init-Wallet: Found MASTER_ACCOUNT's wallet for the GlobalTrustCoin node_id on: 127.0.0.1
RPC Connected.

when i try login 

GET /login 304 16.792 ms - -
GET /wallet/images/background.jpg 200 6.544 ms - 2551
POST /login 302 112.682 ms - 56
GET /login 200 2.240 ms - 2959
GET /wallet/images/background.jpg 200 2.002 ms - 2551

no thing happend just again redirect to login page
